name: flame_visual_fx
resolution: workspace
description: A collection of high-performance, cross-platform Canvas-based Decorators for Flame engine (Outlines, Neon Glows, Ghost Trails, Holographic Glitches, and Dissolves).
version: 1.0.0
publish_to: none
homepage: https://github.com/
repository: https://github.com/

environment:
  sdk: ^3.11.0
  flutter: ">=3.10.0"

dependencies:
  flame: any
  meta: ^1.11.0
  flame_unified_real_time: any
  vector_math: ^2.1.0
  composite_atlas:
    path: ../composite_atlas
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  shaders:
    - lib/src/shaders/hologram.frag
